version: '3'
services:
  posteio:
    image: analogic/poste.io
    ports:
      - "25:25"
      - "6968:80"
      - "6969:443"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      - TZ=Europe/Prague
    volumes:
      - /opt/mail/data:/data
    restart: always
